CREATE SCHEMA userDatabase;
USE userDatabase;
CREATE TABLE users
( userID INTEGER PRIMARY KEY NOT NULL AUTO_INCREMENT,
lastName VARCHAR(255) NOT NULL,
firstName VARCHAR(255) NOT NULL,
address VARCHAR(255) NOT NULL,
city VARCHAR(255) NOT NULL );
